name: Continuous Integration

on:
  # Trigger the workflow on push or pull request or custom
  push:
    branches:
      main
  pull_request_target:
    branches:
      main
  workflow_dispatch:

jobs:
  Prettier:
    name: Run Prettier
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3

      - name: Set up Node.js
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3
        with:
          node-version: 17

      - name: Install pnpm
        run: npm i -g pnpm

      # Prettier must be in `package.json`
      - name: Install Node.js dependencies
        run:  pnpm i

      - name: Run Prettier
        run: pnpm run pretty

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "style: pretty please"
          branch: prettier
          delete-branch: true
          branch-suffix: short-commit-hash
          title: "style: pretty please"
          body: "pretty pretty prettier"
          reviewers: EvolutionX-10
