name: Continuous Integration

on:
  # Trigger the workflow on push or pull request or custom
  push:
    branches: [main]
    paths:
      - '*.ts'
  pull_request_target:
    branches:
      main
    paths:
      - '*ts'
  workflow_dispatch:

jobs:
  Prettier:
    name: Run Prettier
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3

      - name: Set up Node.js
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
        with:
          node-version: 17

      - name: Install pnpm
        run: npm i -g yarn

      # Prettier must be in `package.json`
      - name: Install Node.js dependencies
        run:  yarn --immutable

      - name: Run Prettier
        run: yarn pretty

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "style: pretty please"
          branch: prettier
          delete-branch: true
          branch-suffix: short-commit-hash
          title: "style: pretty please"
          body: "pretty pretty prettier"
          reviewers: EvolutionX-10
